/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IGBCLab__factory } from "./IGBCLab__factory";
export { IRandomizer__factory } from "./IRandomizer__factory";
