/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IRandomizer,
  IRandomizerInterface,
} from "../../../contracts/interfaces/IRandomizer";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_for",
        type: "address",
      },
    ],
    name: "clientDeposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "clientWithdrawTo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "callbackGasLimit",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "confirmations",
        type: "uint256",
      },
    ],
    name: "request",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "callbackGasLimit",
        type: "uint256",
      },
    ],
    name: "request",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRandomizer__factory {
  static readonly abi = _abi;
  static createInterface(): IRandomizerInterface {
    return new utils.Interface(_abi) as IRandomizerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRandomizer {
    return new Contract(address, _abi, signerOrProvider) as IRandomizer;
  }
}
